export default [
    {
        id: 1,
        title: "Атака",
        lvlMax: 120,
        currentLvl: 12,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/attack/attack.svg",
        exp: 150,
    },
    {
        id: 2,
        title: "Сила",
        lvlMax: 120,
        currentLvl: 11,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/strength/strength.svg",
        exp: 150,
    },
    {
        id: 3,
        title: "Защита",
        lvlMax: 120,
        currentLvl: 5,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/defence/defence.svg",
        exp: 150,
    },
    {
        id: 4,
        title: "Здоровье",
        lvlMax: 120,
        currentLvl: 5,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/hitpoints/hitpoints.svg",
        exp: 150,
    },
    {
        id: 5,
        title: "Дальний бой",
        lvlMax: 120,
        currentLvl: 5,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/ranged/ranged.svg",
        exp: 150,
    },
    {
        id: 6,
        title: "Магия",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/magic/magic.svg",
        exp: 150,
    },
    {
        id: 7,
        title: "Молитва",
        lvlMax: 120,
        currentLvl: 111,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/prayer/prayer.svg",
        exp: 150,
    },
    {
        id: 8,
        title: "Убийца",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/slayer/slayer.svg",
        exp: 150,
    },
];