export default [
    {
        id: 1,
        title: "Рубка леса",
        lvlMax: 120,
        currentLvl: 12,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/woodcutting/woodcutting.svg",
        exp: 150,
    },
    {
        id: 2,
        title: "Рыбалка",
        lvlMax: 120,
        currentLvl: 11,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/fishing/fishing.svg",
        exp: 150,
    },
    {
        id: 3,
        title: "Разведение костра",
        lvlMax: 120,
        currentLvl: 115,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/firemaking/firemaking.svg",
        exp: 150,
    },
    {
        id: 4,
        title: "Кулинария",
        lvlMax: 120,
        currentLvl: 5,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/cooking/cooking.svg\n",
        exp: 150,
    },
    {
        id: 5,
        title: "Горное дело",
        lvlMax: 120,
        currentLvl: 5,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/mining/mining.svg",
        exp: 150,
    },
    {
        id: 6,
        title: "Кузнечное дело",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/smithing/smithing.svg",
        exp: 150,
    },
    {
        id: 7,
        title: "Воровство",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/thieving/thieving.svg",
        exp: 150,
    },
    {
        id: 8,
        title: "Изготовление стрел",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/fletching/fletching.svg",
        exp: 150,
    },
    {
        id: 9,
        title: "Ремесла",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/crafting/crafting.svg",
        exp: 150,
    },
    {
        id: 10,
        title: "Изготовление рун",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/runecrafting/runecrafting.svg",
        exp: 150,
    },
    {
        id: 11,
        title: "Травничество",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/herblore/herblore.svg",
        exp: 150,
    },
    {
        id: 12,
        title: "Ловкость",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/agility/agility.svg",
        exp: 150,
    },
    {
        id: 13,
        title: "Призыв",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/summoning/summoning.svg",
        exp: 150,
    },
    {
        id: 14,
        title: "Астрология",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/astrology/astrology.svg",
        exp: 150,
    },
    {
        id: 15,
        title: "Альтернативная магия",
        lvlMax: 120,
        currentLvl: 1,
        imgsource: "https://cdn.melvor.net/core/v018/assets/media/skills/magic/magic.svg",
        exp: 150,
    },
]